name: Propose Stable Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options:
          - build
          - minor
          - major
jobs:
  update_version:
    uses: neongeckocom/.github/.github/workflows/propose_semver_release.yml@master
    with:
      release_type: ${{ inputs.release_type }}
      version_file: ovos_plugin_manager/version.py
      alpha_var: VERSION_ALPHA
      build_var: VERSION_BUILD
      minor_var: VERSION_MINOR
      major_var: VERSION_MAJOR
      update_changelog: True
      branch: dev

  pull_changes:
    needs: update_version
    uses: neongeckocom/.github/.github/workflows/pull_master.yml@master
    with:
      pr_assignee: ${{ github.actor }}
      pr_draft: false
      pr_title: ${{ needs.update_version.outputs.version }}
      pr_body: ${{ needs.update_version.outputs.changelog }}
